lib/book_search_web/router.ex
defmodule BookSearchWeb.Router do
  use BookSearchWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {BookSearchWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", BookSearchWeb do
    pipe_through :browser

    get "/", PageController, :index
    resources "/authors", AuthorController
    resources "/books", BookController
    resources "/tags", TagController
  end

  # Other scopes may use custom stacks.
  # scope "/api", BookSearchWeb do
  #   pipe_through :api
  # end
end

lib/book_search/books.ex
defmodule BookSearch.Books do
  @moduledoc """
  The Books context.
  """

  import Ecto.Query, warn: false
  alias BookSearch.Repo

  alias BookSearch.Books.Book

  @doc """
  Returns the list of books.

  ## Examples

      iex> list_books()
      [%Book{}, ...]

  """
  def list_books do
    Book
    |> preload(:author)
    |> Repo.all()
  end

  @doc """
  Gets a single book.

  Raises `Ecto.NoResultsError` if the Book does not exist.

  ## Examples

      iex> get_book!(123)
      %Book{}

      iex> get_book!(456)
      ** (Ecto.NoResultsError)

  """
  def get_book!(id), do: Repo.get!(Book, id)

  @doc """
  Creates a book.

  ## Examples

      iex> create_book(%{field: value})
      {:ok, %Book{}}

      iex> create_book(%{field: bad_value})
      {:error, %Ecto.Changeset{}}

  """
  def create_book(attrs \\ %{}, tags \\[]) do
    IO.inspect(attrs, label: "attrs in create_book in business logic : ")
    %Book{}
    |> Book.changeset(attrs, tags)
    |> Repo.insert
  end

  @doc """
  Updates a book.

  ## Examples

      iex> update_book(book, %{field: new_value})
      {:ok, %Book{}}

      iex> update_book(book, %{field: bad_value})
      {:error, %Ecto.Changeset{}}

  """
  def update_book(%Book{} = book, attrs) do
    book
    |> Book.changeset(attrs)
    |> Repo.update()
  end

  @doc """
  Deletes a book.

  ## Examples

      iex> delete_book(book)
      {:ok, %Book{}}

      iex> delete_book(book)
      {:error, %Ecto.Changeset{}}

  """
  def delete_book(%Book{} = book) do
    Repo.delete(book)
  end

  @doc """
  Returns an `%Ecto.Changeset{}` for tracking book changes.

  ## Examples

      iex> change_book(book)
      %Ecto.Changeset{data: %Book{}}

  """
  def change_book(%Book{} = book, attrs \\ %{}) do
    Book.changeset(book, attrs)
  end
end

lib/book_search/books/book.ex
defmodule BookSearch.Books.Book do
  use Ecto.Schema
  import Ecto.Changeset

  schema "books" do
    field :title, :string
    belongs_to :author, BookSearch.Authors.Author

    many_to_many :tags, BookSearch.Tags.Tag, join_through: "book_tags", on_replace: :delete
    has_one :book_content, BookSearch.Books.BookContent
    timestamps()
  end

  @doc false
  def changeset(book, attrs, tags \\[]) do
    book
    |> cast(attrs, [:title, :author_id])
    |> put_assoc(:tags, tags)
    |> cast_assoc(:book_content)
    |> validate_required([:title])
  end
end

lib/book_search/books/book_content.ex
defmodule BookSearch.Books.BookContent do
  use Ecto.Schema
  import Ecto.Changeset

  schema "book_content" do
    field :full_text, :string

    belongs_to :book, BookSearch.Books.Book

    # timestamps()
  end

  @doc false
  def changeset(book_content, attrs) do
    book_content
    |> cast(attrs, [:full_text])
    |> validate_required([:full_text])
  end
end

lib/book_search_web/controllers/book_controller.ex
defmodule BookSearchWeb.BookController do
  use BookSearchWeb, :controller

  alias BookSearch.{Authors, Books, Tags}
  alias BookSearch.Books.Book

  def index(conn, _params) do
    books =
      Books.list_books()
      |> BookSearch.Repo.preload([:author])
    render(conn, "index.html", books: books)
  end

  def new(conn, _params) do
    changeset = Books.change_book(%Book{})
    authors = Authors.list_authors()
    render(conn, "new.html", changeset: changeset, authors: authors)
  end

  def create(conn, params = %{"book" => book_params}) do
    IO.inspect(params, label: "Params in Book Controller")

    {tag_ids, book_params} = book_params |> Map.pop("tags", [])
    tags = tag_ids |> Enum.map(fn id -> Tags.get_tag!(id) end)

    case Books.create_book(book_params, tags) do
      {:ok, book} ->
        conn
        |> put_flash(:info, "Book created successfully.")
        |> redirect(to: Routes.book_path(conn, :show, book))

      {:error, %Ecto.Changeset{} = changeset} ->
        authors = Authors.list_authors()
        render(conn, "new.html", changeset: changeset, authors: authors)
    end
  end

  def show(conn, %{"id" => id}) do
    book =
      Books.get_book!(id)
      |> BookSearch.Repo.preload([:author, :tags, :book_content])
    render(conn, "show.html", book: book)
  end

  def edit(conn, %{"id" => id}) do
    book =
      Books.get_book!(id)
      |> BookSearch.Repo.preload([:book_content, :tags])

      changeset = Books.change_book(book)
    authors = Authors.list_authors()
    render(conn, "edit.html", book: book, changeset: changeset, authors: authors)
  end

  def update(conn, %{"id" => id, "book" => book_params}) do
    book = Books.get_book!(id)

    case Books.update_book(book, book_params) do
      {:ok, book} ->
        conn
        |> put_flash(:info, "Book updated successfully.")
        |> redirect(to: Routes.book_path(conn, :show, book))

      {:error, %Ecto.Changeset{} = changeset} ->
        authors = Authors.list_authors()
        render(conn, "edit.html", book: book, changeset: changeset, authors: authors)
    end
  end

  def delete(conn, %{"id" => id}) do
    book = Books.get_book!(id)
    {:ok, _book} = Books.delete_book(book)

    conn
    |> put_flash(:info, "Book deleted successfully.")
    |> redirect(to: Routes.book_path(conn, :index))
  end
end

lib/book_search_web/views/book_view.ex
defmodule BookSearchWeb.BookView do
  use BookSearchWeb, :view

  
end

lib/book_search_web/templates/book/edit.html.heex
<h1>Edit Book</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.book_path(@conn, :update, @book)) %>

<span><%= link "Back", to: Routes.book_path(@conn, :index) %></span>

lib/book_search_web/templates/book/form.html.heex
<.form let={f} for={@changeset} action={@action}>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <%= label f, :title %>
  <%= text_input f, :title %>
  <%= error_tag f, :title %>

  <%= label f, :author_id %>
  <%= select f, :author_id, Enum.map(@authors, fn author -> {author.name, author.id} end), prompt: "Select an author" %>
  <%= error_tag f, :author_id %>

  <%= label f, :tags %>
alias BookSearchWeb.TagView
  <%= multiple_select f, :tags, BookSearchWeb.TagView.tag_options(), selected: [] %>
  <%= error_tag f, :tags %>

    <!--
    Generate form inputs for the "book_content" field of the form represented by "f".
    The form helper function "inputs_for" will pass a `Phoenix.HTML.Form` struct bound to `book_content_form` as an argument to the form helpers.
  -->
  <%= inputs_for f, :book_content, fn book_content_form -> %>
    <!-- Generate a label for the "full_text" field of the nested "book_content" field -->
    <%= label book_content_form, :full_text %>
    <!-- Generate a text input for the "full_text" field of the nested "book_content" field -->
    <%= text_input book_content_form, :full_text %>
    <!-- Generate an error tag for the "full_text" field of the nested "book_content" field -->
    <%= error_tag book_content_form, :full_text %>
  <!-- Close the block passed to "inputs_for" -->
  <% end %>

  <div>
    <%= submit "Save" %>
  </div>
</.form>

lib/book_search_web/templates/book/index.html.heex
<h1>Listing Books</h1>

<table>
  <thead>
    <tr>
      <th>Author</th>
      <th>Title</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for book <- @books do %>
    <tr>
      <td><%= if book.author, do: book.author.name %></td>
      <td><%= book.title %></td>

      <td>
        <span><%= link "Show", to: Routes.book_path(@conn, :show, book) %></span>
        <span><%= link "Edit", to: Routes.book_path(@conn, :edit, book) %></span>
        <span><%= link "Delete", to: Routes.book_path(@conn, :delete, book), method: :delete, data: [confirm: "Are you sure?"] %></span>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

<span><%= link "New Book", to: Routes.book_path(@conn, :new) %></span>

lib/book_search_web/templates/book/new.html.heex
<h1>New Book</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.book_path(@conn, :create)) %>

<span><%= link "Back", to: Routes.book_path(@conn, :index) %></span>

lib/book_search_web/templates/book/show.html.heex
<h1>Show Book</h1>

<ul>
  <li>
    <strong>Author:</strong>
    <%= if @book.author, do: @book.author.name %>
  </li>

  <li>
    <strong>Title:</strong>
    <%= @book.title %>
  </li>

  <li>
    <strong>Tags:</strong>
    <ul>
      <%= for tag <- @book.tags do %>
        <li><%= link tag.name, to: Routes.tag_path(@conn, :show, tag) %></li>
      <% end %>
    </ul>
  </li>


  <!-- If the @book object has a "book_content" field, render the following HTML -->
  <%= if @book.book_content do %>
    <li>
      <strong>Full Text:</strong>
      <!-- Render the "full_text" field of the "book_content" map -->
      <%= @book.book_content.full_text %>
    </li>
  <!-- Close the if statement -->
  <% end %>
</ul>


<span><%= link "Edit", to: Routes.book_path(@conn, :edit, @book) %></span> |
<span><%= link "Back", to: Routes.book_path(@conn, :index) %></span>